baseURL = 'https://blog.niubi.dev/'
languageCode = 'zh-CN'
defaultContentLanguage = 'zh-cn'
title = '陈'
description = '陈'
theme = "LoveIt"

# Menu config
[menu]
  [[menu.main]]
    weight = 2
    identifier = "tags"
    pre = ""
    post = ""
    name = "标签"
    url = "/tags/"
    title = ""
  [[menu.main]]
    weight = 3
    identifier = "categories"
    pre = ""
    post = ""
    name = "分类"
    url = "/categories/"
    title = ""
[params]
  title = '陈'
  description = '陈'
  [params.author]
    name = "陈"
  #  email = ""
  #  link = ""
  [params.header.title]
    name = '陈'
  [params.footer]
    hugo = false
    copyright = true
    custom = '<script async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-2592788502290192" crossorigin="anonymous"></script>'
  [params.page.share]
    enable = false
  [params.home.profile]
    subtitle = ''
  [params.analytics]
    enable = true
    [params.analytics.google]
      id = "G-7EER0471GM"
      # whether to anonymize IP
      # 是否匿名化用户 IP
      anonymizeIP = true
# Markup related configuration in Hugo
[markup]
  # Syntax Highlighting (https://gohugo.io/content-management/syntax-highlighting)
  [markup.highlight]
    # false is a necessary configuration (https://github.com/dillonzq/LoveIt/issues/158)
    noClasses = false

